package br.com.cifras;

import br.com.cifras.group.model.Group;
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.transaction.Transactional;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration Test explicitly using our custom PostgresTestResource (Testcontainers).
 * Ensures that explicit testcontainer configuration works seamlessly with Panache/Hibernate.
 */
@QuarkusTest
@QuarkusTestResource(PostgresTestResource.class)
public class DatabaseIntegrationTest {

    @Test
    @Transactional
    public void testExplicitTestcontainerDatabaseConnection() {
        // Simple write to the database to ensure our testcontainer PostgreSQL is running and mapped correctly
        Group group = new Group();
        group.name = "Testcontainers Group";
        group.ownerId = "user-123";
        group.persist();

        assertNotNull(group.id, "ID should be generated by the database");
        assertTrue(group.isPersistent(), "Entity should be persistent");
        
        // Clean up
        group.delete();
    }
}
