-- Supabase RLS Setup Script
-- Generated by Gemini CLI to secure the project 'lyjekqxblyytyvyobtnw'
-- Rules:
-- 1. Songs: Viewable by all authenticated users, manageable only by owner.
-- 2. Groups/Playlists: Viewable only by members or owners.

-- 1. Habilitar RLS em todas as tabelas
ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlist_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_invitations ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- POLÍTICAS PARA SONGS (Músicas)
-- ==========================================

-- Qualquer usuário logado pode ver todas as músicas (Compartilhamento)
CREATE POLICY "Músicas visíveis para todos os autenticados"
ON public.songs FOR SELECT
TO authenticated
USING (true);

-- Apenas o criador pode inserir, editar ou deletar suas músicas
CREATE POLICY "Apenas criador gerencia suas músicas"
ON public.songs FOR ALL
TO authenticated
USING (auth.uid() = userid)
WITH CHECK (auth.uid() = userid);


-- ==========================================
-- POLÍTICAS PARA GRUPOS (Grupos)
-- ==========================================

-- Membros do grupo podem ver o grupo
CREATE POLICY "Membros veem seus grupos"
ON public.grupos FOR SELECT
TO authenticated
USING (
  auth.uid() = ownerid OR
  EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_members.group_id = grupos.id
    AND group_members.user_id = auth.uid()
  )
);

-- Donos podem gerenciar seus grupos
CREATE POLICY "Donos gerenciam grupos"
ON public.grupos FOR ALL
TO authenticated
USING (auth.uid() = ownerid);


-- ==========================================
-- POLÍTICAS PARA PLAYLISTS
-- ==========================================

-- Playlists são visíveis para o dono OU membros do grupo associado
CREATE POLICY "Playlists visíveis para dono ou grupo"
ON public.playlists FOR SELECT
TO authenticated
USING (
  auth.uid() = userid OR
  (
    group_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM public.group_members
      WHERE group_members.group_id = playlists.group_id
      AND group_members.user_id = auth.uid()
    )
  )
);

-- Apenas o dono pode editar/deletar a playlist
CREATE POLICY "Dono gerencia suas playlists"
ON public.playlists FOR ALL
TO authenticated
USING (auth.uid() = userid);

-- ==========================================
-- POLÍTICAS PARA PLAYLIST_SONGS (Relação música-playlist)
-- ==========================================

-- Visibilidade segue a da playlist
CREATE POLICY "Músicas da playlist seguem visibilidade da mesma"
ON public.playlist_songs FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.playlists
    WHERE playlists.id = playlist_songs.playlist_id
  )
);

-- Edição segue a do dono da playlist
CREATE POLICY "Dono da playlist gerencia suas músicas"
ON public.playlist_songs FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.playlists
    WHERE playlists.id = playlist_songs.playlist_id
    AND playlists.userid = auth.uid()
  )
);
